packages:
  - packages/@prigas.generator
  - packages/@prigas.restless
  - packages/@prigas.sample
  - packages/@prigas.server
  - packages/@prigas.server.api
  - packages/@prigas.server.frontend
  - packages/libs.result
  - packages/prigas
  - packages/tools.project
